name: gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'
      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'

      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release --public-url nes-emu
      
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/